#!/bin/bash
## Crafted (c) 2022 by Daitanlabs - We are stronger together
## Prepared : Roberto Nogueira
## File     : install
## Project  : project-site-manager
## Reference: bash
## Depends  : todotxt, tree
## Purpose  : Install site manager.

# set -x

source ./today
OS=`uname`

today_install(){
  case $1 in
    --version|-v|v|version)
      today_install.version
      ;;
    --help|-h|h|help)
      today_install.help
      ;;
    $TODAY_INSTALL_METHODS)
      if [ -z "$1" ]; then
        if ! test -f $HOME/.site; then
          echo -e "\033[1;92m==> \033[0m\033[1;39mInstalling \"today manager\" \033[0m"
          echo ""
          echo "" >> $HOME/.bashrc
          echo "# today manager" >> $HOME/.bashrc
          echo "test -f $HOME/.site && source $HOME/.site" >> $HOME/.bashrc
        else  
          echo -e "\033[1;92m==> \033[0m\033[1;39mUpdating \"today manager\" \033[0m"
          echo ""
        fi  
        cp site $HOME/.site
        source $HOME/.bashrc
        cowsay $SITE_UPDATE_MESSAGE
      else  
        local methods="+($(today_install.methods))"
        case $1 in
          $methods)
            site_install.$1
            ;;
          *)
            printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${3}"
            ;;  
        esac
      fi  
      ;;
    *)
      if [ -z "$1" ]; then
        site.print
      else   
        printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${1}"
      fi  
      ;;
  esac
}
today_install.methods(){
  echo "help|deps|version"
}
today_install.help(){
  printf "\e[1;37m%s \e[0m\n" "Crafted (c) 2021 by Daitanlabs - We are stronger together"
  site_install.version
  printf "\e[1;36m%s \e[0m%s\n" "today_install" "[$(today_install.methods)]"
  printf "::\n"  
  printf "\e[0;32m%s \e[4m%s\e[0m\e[0m\n" "homepage" "https://github.com/enogrob/project-today-manager"
  printf "\n"
}      
today_install.deps(){
 if ! test -f /usr/local/bin/cowsay && ! test -f /usr/games/cowsay; then
   echo -e "\033[1;92m==> \033[0m\033[1;39mInstalling \"cowsay\" \033[0m"
   echo ""
   if [ "$OS" == 'Darwin' ]; then
     brew install cowsay
   else  
     sudo apt-get install cowsay
   fi
 fi
 
 if ! test -f /usr/local/bin/todo.sh && ! test -f /usr/bin/todo.sh; then
   echo -e "\033[1;92m==> \033[0m\033[1;39mInstalling \"todo.txt-cli\" \033[0m"
   echo ""
   if [ "$OS" == 'Darwin' ]; then
     brew install todo-txt
     cp -n /usr/local/opt/todo-txt/todo.cfg ~/.todo.cfg
   else  
     git clone git@github.com:todotxt/todo.txt-cli.git
     cd todo.txt-cli
     make 
     sudo make install
     make test
     cd ..
     rm -rf todo.txt-cli
   fi
 fi
}
today_install.version(){
  printf "\e[0;37m%s \e[0m%s\n" "Today Install" "$TODAY_VERSION"
  printf "\n"
}

export TODAY_INSTALL_METHODS="+($(today_install.methods))"
