#!/bin/bash
## Crafted (c) 2021 by Daitanlabs - We are stronger together
## Prepared : Roberto Nogueira
## File     : today
## Project  : project-today-manager
## Reference: bash
## Depends  : tree, todotxt, xclip
## Purpose  : Help to manage gtd process flow implemented in the file system.

# set -x

export TODAY_VERSION=v1.0.07
export TODAY_VERSION_DATE=2022.01.04
export TODAY_UPDATE_MESSAGE="Initial version"

export TODAY_THINGS=$HOME/Things

export TODAY_INBOX=$TODAY_THINGS/Inbox
export TODAY_LOGBOOK=$TODAY_THINGS/Logbook
export TODAY_PROJECTS=$TODAY_THINGS/Projects
export TODAY_SCHEDULED=$TODAY_THINGS/Scheduled
export TODAY_SOMEDAY=$TODAY_THINGS/Someday
export TODAY=$TODAY_THINGS/Today

alias tdy='today'
alias tdyl='today.list'
alias tdyi='today.start'
alias tdye='today.stop'

alias tdp='projects'
alias tdpl='projects.list'
alias tdpn='projects.new'

alias tdl='logbook'
alias tdll='logbook.list'

alias tdsd='someday'
alias tdsdl='someday.list'
alias tdsdi='someday.start'
alias tdsde='someday.stop'
alias tdsdt='someday.today'

alias tdi='inbox'
alias tdic='inbox.collect'
alias tdil='inbox.list'

alias tds='scheduled'
alias tdsl='scheduled.list'
alias tdsi='scheduled.start'
alias tdse='scheduled.stop'
alias tdse='scheduled.today'

inbox(){ pushd $TODAY_INBOX; }
inbox.methods(){ echo "collect|help|list"; }
inbox.collect(){
  local project=$1
  if test -d $TODAY_INBOX;
    mv $1 $TODAY_INBOX
    ls -la $TODAY_INBOX
  fi
}
inbox.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "inbox" "[$(inbox.methods)]"; }
inbox.list(){ ls -la $TODAY_INBOX; }

logbook(){ pushd $TODAY_LOGBOOK; }
logbook.methods(){ echo "help|list"; }
logbook.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "logbook" "[$(logbook.methods)]"; }
logbook.list(){ ls -la $TODAY_LOGBOOK; }

projects(){ pushd $TODAY_PROJECTS; }
projects.methods(){ echo "help|list|new"; }
projects.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "projects" "[$(projects.methods)]"; }
projects.list(){ ls -la $TODAY_PROJECTS; }
projects.new(){
  local project=$1

  if [ "$PWD" == "$TODAY_INBOX" ]; then
    ! test -d $TODAY_PROJECTS/$1 && mkdir -p $TODAY_PROJECTS/$1
    mv * $TODAY_PROJECTS/$1
    pushd $TODAY_PROJECTS/$1
  fi
}

scheduled(){ pushd $TODAY_SCHEDULED; }
scheduled.methods(){ echo "end|help|list|start|today"; }
scheduled.end(){
  local project=$(basename $(pwd))
  if test -L $TODAY_SCHEDULED/$project;
    rm $TODAY_SCHEDULED/$project
  fi
}
scheduled.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "scheduled" "[$(scheduled.methods)]"; }
scheduled.list(){ tree -L 1 $TODAY_SCHEDULED; }
scheduled.start(){
  local project=$(basename $(pwd))
  if test -L $TODAY_PROJECTS/$project;
    ln -sf $TODAY_PROJECTS/$project $TODAY_SCHEDULED/$project
  fi
}
scheduled.today(){
  local project=$(basename $(pwd))
  if test -L $TODAY_SCHEDULED/$project;
    ln -sf $(readlink -f $TODAY_SCHEDULED/$project) $TODAY/$project
    rm $TODAY_SCHEDULED/$project
  fi
}

someday(){ pushd $TODAY_SOMEDAY; }
someday.methods(){ echo "end|help|list|start|today"; }
someday.end(){
  local project=$(basename $(pwd))
  if test -L $TODAY_SOMEDAY/$project;
    rm $TODAY_SOMEDAY/$project
  fi
}
someday.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "scheduled" "[$(scheduled.methods)]"; }
someday.list(){ tree -L 1 $TODAY_SCHEDULED; }
someday.start(){
  local project=$(basename $(pwd))
  if test -L $TODAY_PROJECTS/$project;
    ln -sf $TODAY_SOMEDAY/$project $TODAY_PROJECTS/$project
  fi
}
someday.today(){
  local project=$(basename $(pwd))
  if test -L $TODAY_SOMEDAY/$project;
    ln -sf $(readlink -f $TODAY_SOMEDAY/$project) $TODAY/$project
    rm $TODAY_SOMEDAY/$project
  fi
}

# today
today(){
  local site_methods="+($(today.methods))"
  local param_methods="+($(! test -z "$1" && $1.methods))"
  case $1 in
    --version|-v|v|version)
      today.version
      ;;
    --help|-h|h|help)
      printf "\e[1;37m%s \e[0m\n" "Crafted (c) 2021 by Daitanlabs - We are stronger together"
      site.version
      printf "\e[1;37m%s \e[0m%s\n" "today" "[$(today.help)]" 
      printf "::\n"  
      printf "\e[1;37m%s \e[0m%s\n" "inbox" "[$(inbox.help)]" 
      printf "\e[1;37m%s \e[0m%s\n" "logbook" "[$(logbook.help)]" 
      printf "\e[1;37m%s \e[0m%s\n" "projects" "[$(projects.help)]" 
      printf "\e[1;37m%s \e[0m%s\n" "scheduled" "[$(scheduled.help)]" 
      printf "\e[1;37m%s \e[0m%s\n" "someday" "[$(someday.help)]" 
      printf "::\n"  
      printf "\e[0;32m%s \e[4m%s\e[0m\e[0m\n" "homepage" "http://bitbucket.wrs.com/users/rmartins/repos/project-today-manager"
      printf "\n"
      ;;
    $today_methods)
      if [ -z "$2" ]; then
        $1 
      else  
        case $2 in
          $param_methods)
            $1.$2 ${@:3}
            ;;
          *)
            printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${2}"
            ;;  
        esac
      fi  
      ;;
    *)
      if [ -z "$1" ]; then
        pushd $TODAY
      else   
        printf " \e[0;31m%s \e[0m%s\n" "=>" "invalid parameter ${1}"
      fi  
      ;;
  esac
}
today.init(){
  ! test -d $TODAY_THINGS && mkdir -p $TODAY_THINGS

  ! test -d $TODAY_INBOX && mkdir -p $TODAY_INBOX
  ! test -d $TODAY_LOGBOOK && mkdir -p $TODAY_LOGBOOK
  ! test -d $TODAY_PROJECTS && mkdir -p $TODAY_PROJECTS
  ! test -d $TODAY_SCHEDULED && mkdir -p $TODAY_SCHEDULED
  ! test -d $TODAY_SOMEDAY && mkdir -p $TODAY_SOMEDAY
  ! test -d $TODAY && mkdir -p $TODAY

  ! test -L $HOME/Inbox && ln -sf $TODAY_INBOX $HOME/Inbox
  ! test -L $HOME/Logbook && ln -sf $TODAY_LOGBOOK $HOME/Logbook
  ! test -L $HOME/Projects && ln -sf $TODAY_PROJECTS $HOME/Projects
  ! test -L $HOME/Someday && ln -sf $TODAY_SOMEDAY $HOME/Someday
  ! test -L $HOME/Scheduled && ln -sf $TODAY_SCHEDULED $HOME/Scheduled
  ! test -L $HOME/Today && ln -sf $TODAY $HOME/Today
}
today.methods(){ echo "end|help|list|print|start|version"; }
today.end(){
  local project=$(basename $(pwd))
  if test -L $TODAY/$project;
    ln -sf $(readlink -f $TODAY/$project) $TODAY_LOGBOOK/$project
    rm $TODAY/$project
  fi
}
today.help(){ printf "\e[1;37m%s   \e[0m \e[1;36m%s\e[0m\n" "today" "[$(today.methods)]"; }
today.list(){ tree -L 1 $TODAY; }
today.print(){
  echo -e "today: \e[4m\e[1;37m$USER@$(hostname)\e[0m\e[0m" 
  printf ""  
}
today.start(){
  local project=$(basename $(pwd))
  if test -d $TODAY_PROJECTS/$project;
    ln -sf $TODAY_PROJECTS/$project $TODAY/$project
  fi
}
today.version(){
  printf "\e[0;37m%s \e[0m%s\n" "Today" "$TODAY_VERSION"
  printf "\n"
}

today.init